### PR TITLE
fix loading of a href element

### PR DESCRIPTION
**Pull request by vavrecan**
it can happen, that this function will fail in case of <abrr> <a></a> etc or or other issues. i would say it is a good idea to do additional error checking so that $a->getAttribute will not throw exception when a is null.

### CODE REVIEW

**Comment by Sommerregen** [comment]
@vavrecan Can you give me an example, when such a thing happens?

**Comment by vavrecan** [comment]
Iirc If tag in source is &lt;abbr&gt; &lt;/a&gt; or so

**Review by Sommerregen — COMMENTED** [review]
Hi @vavrecan,

I think what you actually mean is:

```php
$a = $dom->getElementsByTagName('a');
if ($a->length == 0) {
  return $match[0];
}
$a = $a->item(0);
```

as there is no check yet in the code for "emptyness" in the code. However, If found a bug with `<abbr>`: obviously the regex is wrong and has to be `<a(?:\s[^>]*)?>.*?</a>`.

Can you check my changes in the develop branch?

**Comment by Sommerregen** [comment]
Merged. Thanks! :+1:

**Pull request closed without merging**
